trigger:
  tags:
    include: ['*']

name:  $[format('{0:yyyyMMdd\-HHmmss}', pipeline.startTime)]

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    curl -L https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb -o pacman.deb
    sudo apt update
    sudo dpkg -i pacman.deb
    sudo dkp-pacman -Sy
    sudo dkp-pacman -S nds-dev --noconfirm
  displayName: 'Setup environment'

- script: |
    echo $(COMMIT_TAG)
    echo $(BUILD_SOURCEVERSION)
  displayName: 'Echo Variables'

- script: |
    export DEVKITPRO="/opt/devkitpro"
    export DEVKITARM="/opt/devkitpro/devkitARM"
    make
    cp GodMode9i.nds $(Build.ArtifactStagingDirectory)/GodMode9i.nds
    ls
  displayName: 'Build GM9i-Term256'
