name: GM9i-term256 Binary Compilation

on:
  push:
    branches:
    - master
    - release/*
    tags:
      - v*

jobs:
  buildApplet:
    name: Build GM9i-term256
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Install devkit(Pro/ARM) and libnds
      run: |
       curl -L https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb -o pacman.deb
       sudo apt update
       sudo dpkg -i pacman.deb
       sudo dkp-pacman -Sy
       sudo dkp-pacman -S nds-dev --noconfirm
    - name: make
      run: |
        export DEVKITPRO="/opt/devkitpro"
        export DEVKITARM="/opt/devkitpro/devkitARM"
        make
        mkdir gm9i-term256
        cp GodMode9i.nds gm9i-term256/GodMode9i.nds
    - uses: actions/upload-artifact@master
      with:
        name: GM9i-term256-${{ github.sha }}
        path: gm9i-term256/
